AWSTemplateFormatVersion : 2010-09-09
Transform: AWS::Serverless-2016-10-31
Resources:
  post:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs14.x
      Handler: dist/index.handler
      Events:
        Api:
          Type: HttpApi